import { Column, Entity, JoinColumn, ManyToOne, PrimaryColumn } from "typeorm";
import { User } from "./user.entity";

/**
 * Maps to the `refresh_tokens` table. PK is generated by `refresh_tokens_seq`
 * sequence (Flyway V3). A TypeORM subscriber assigns the nextval before insert.
 */
@Entity("refresh_tokens")
export class RefreshToken {
  @PrimaryColumn({ type: "bigint", name: "id" })
  id: number;

  @Column({ unique: true, nullable: false })
  token: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: "user_id" })
  user: User;

  @Column({ name: "expires_at", type: "timestamptz", nullable: false })
  expiresAt: Date;

  @Column({ nullable: false, default: false })
  revoked: boolean;
}
