import {
  Column,
  CreateDateColumn,
  Entity,
  OneToMany,
  PrimaryColumn,
  UpdateDateColumn,
} from "typeorm";
import { Role } from "./role.enum";
import { UserRole } from "./user-role.entity";

/**
 * Maps to the `users` table. The PK is generated by `users_seq` sequence
 * (Flyway V1). A TypeORM subscriber assigns the nextval before insert.
 */
@Entity("users")
export class User {
  @PrimaryColumn({ type: "bigint", name: "id" })
  id: number;

  @Column({ unique: true, nullable: false })
  email: string;

  @Column({ nullable: false })
  password: string;

  @OneToMany(() => UserRole, (ur) => ur.user, {
    eager: true,
    cascade: ["insert", "remove"],
  })
  userRoles: UserRole[];

  @CreateDateColumn({ name: "created_at", nullable: true })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at", nullable: true })
  updatedAt: Date;

  get roles(): Role[] {
    return (this.userRoles ?? []).map((ur) => ur.role as Role);
  }
}
