import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { Post } from "../../posts/entities/post.entity";
import { User } from "../../users/entities/user.entity";

/**
 * Maps to the `comment` table which uses GENERATED BY DEFAULT AS IDENTITY (Flyway V1).
 * The `owner_id` column was added in Flyway V4 and is nullable.
 */
@Entity("comment")
export class Comment {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Post)
  @JoinColumn({ name: "post_id" })
  post: Post;

  @ManyToOne(() => User, { nullable: true, eager: true })
  @JoinColumn({ name: "owner_id" })
  owner: User | null;

  @Column({ nullable: false })
  content: string;

  @CreateDateColumn({ name: "created_at", nullable: true })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at", nullable: true })
  updatedAt: Date;
}
