import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from "typeorm";
import { User } from "../../users/entities/user.entity";

/**
 * Maps to the `posts` table which uses GENERATED BY DEFAULT AS IDENTITY (Flyway V1).
 * TypeORM's @PrimaryGeneratedColumn() works directly with IDENTITY columns.
 */
@Entity("posts")
export class Post {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ nullable: false })
  title: string;

  @Column({ nullable: false })
  body: string;

  @ManyToOne(() => User, { eager: true })
  @JoinColumn({ name: "user_id" })
  owner: User;

  @OneToMany("Comment", (c: any) => c.post)
  comments: any[];

  @CreateDateColumn({ name: "created_at", nullable: true })
  createdAt: Date;

  @UpdateDateColumn({ name: "updated_at", nullable: true })
  updatedAt: Date;
}
